### ISSUE TITLE
PTN files downloaded directly from the playing interface have an extra `--`

### ISSUE THREAD

**Issue by MortenLohne** [NoHatCoder/Playtak#17]
Example downloaded from https://www.playtak.com/games/402707/playtakviewer and clicking the download button:

````
[Site "PlayTak.com"]
[Date "2021.3.5"]
[Player1 "Abyss"]
[Player2 "NohatCoder"]
[Size "7"]
[Result "0-R"]

1. a7 g7
2. d4 c4
3. d5 d3
4. c5 b5
5. e5 b4
6. f6 c3
7. b6 a6
8. Ca5 Cc6
9. f5 d2
10. f7 1c6-1
11. c6 d6
12. d7 c7
13. 1d7-1 1c7-1
14. Cc7 2c6>2
15. c6 Cd7
16. e6 d1
17. 1a5>1 4d6<13
 -- 0-R
````
Not sure how that `--` at the end of the game ended up there, but it's not standard PTN, and seems to occur every time a game ends with white to move. Hopefully it's an easy fix to remove, or replace with `{--}` so that it becomes a PTN comment instead.

**Comment by NoHatCoder** [comment]
And this should also be fixed.
