### ISSUE TITLE
Canvas doesn't render near the bottom

### ISSUE THREAD

**Issue by humanat** [NoHatCoder/Playtak#19]
On many resolutions the Canvas doesn't render a sliver near the bottom, and just displays whatever was there from other tabs, alt-tab, etc.  The html/css looks right, but I suspect there's a rounding issue going on somewhere, possibly in the javascript used to render the background.  I have not been able to find the root cause of this for a long while.

**Comment by NoHatCoder** [comment]
Screenshot?

This is definitely a problem somewhere on your device.

For anyone affected please provide OS, browser, computer manufacturer, screen resolution, UI scaling, CPU model number, graphics card model and graphics card driver version. Note that many modern PCs have two active graphics processors, one built into the CPU by Intel or AMD, and one discrete by AMD or nVidia, in this case there will also be two drivers.

**Comment by humanat** [comment]
It may have something to do with the driver. However, it’s reproducible on multiple devices for multiple users.  And, importantly, it doesn’t happen on any other test site using a full canvas.  So they _is_ something specific about this site that’s interacting badly.

That said, it’s been this way for years, so I don’t think it’s a rush to fix it. 

I’ll get you more details on drivers etc later, and add some screenshots.
