### ISSUE TITLE
Logging in on another device fights with reconnect on previous device

### ISSUE THREAD

**Issue by humanat** [NoHatCoder/Playtak#20]
If we're going to kill previous sessions, we shouldn't let them reconnect and get into a back and forth fight with the new browser instance.

**Comment by NoHatCoder** [comment]
This is supposed to have been fixed long ago. Can you provide steps to reproduce the war?

**Comment by NoHatCoder** [comment]
Ok, I think I had the same issue, I'll look into it later.

**Comment by NoHatCoder** [comment]
Not sure what the issue was, but some defensive coding seems to have done the trick.
