### ISSUE TITLE
PTN Ninja links

### ISSUE THREAD

**Issue by gruppler** [NoHatCoder/Playtak#25]
Line breaks no longer appear to be supported in URL or URL hash. PTN Ninja currently does its best to figure out where the line breaks should be, but it's a complex workaround.

For the ideal ptn.ninja link...
- The PTN would be compressed using `compressToEncodedURIComponent` from [lz-string](https://pieroxy.net/blog/pages/lz-string/index.html)
- The # would be removed from the URL

For the simplest solution, just replacing the line breaks with spaces would resolve the issue.

**Comment by NoHatCoder** [comment]
I don't want to take on another dependency. I have replaced the line breaks and removed the #.
