### ISSUE TITLE
Viewing a game from history on playtak does not log the player in in the UI

### ISSUE THREAD

**Issue by nitzel** [NoHatCoder/Playtak#26]
E.g. navigating to https://playtak.com/games/461685/playtakviewer
Results in
![image](https://user-images.githubusercontent.com/8362046/139530979-f4a5ccfe-0b0e-4d03-9e52-52dbefc56248.png)

**Comment by NoHatCoder** [comment]
Currently that is by design, as you are only allowed to be logged in from one tab. I see how this is a bit unintuitive, but quite a lot of things would have to change to make anything meaningfully better.

**Comment by nitzel** [comment]
Makes sense. Took me a year to notice :D
