### ISSUE TITLE
Format code in /static for consistency

### ISSUE THREAD

**Issue by nitzel** [NoHatCoder/Playtak#5]
Suggestions, please comment know if you disagree
- Use spaces after parameters
- Use 2xSpace for indentation instead of tabs
- Use single quote instead of double quote
- Use string interpolation instead of concatenation

I'd also suggest using ESLint to highlight deviations from the coding standard

**Comment by NoHatCoder** [comment]
Indentation standard is tabs, this is a conversion from previous mixed length space indentation. There are still spaces and misindented code here and there, fixes for those are welcome.

I don't care enough about spaces, single/double quotes, string interpolation and semicolons to make a hard rule about those. Do what you like when you write code, but don't go around changing it in existing code.

One thing I would like changed is the formatting of statements spread over multiple lines. There is code like this:

    verylongfunctionname(param1,
                                       param2,
                                       param3)

If it can't reasonably fit on one line, the opening and the closing of the list should each have their own line, and nothing should be indented for alignment. So reformat to:

    verylongfunctionname(
        param1,
        param2,
        param3
    )

Also, `if` statements should always have brackets.

**Comment by nitzel** [comment]
Okay, tabs it is. I only saw that both was used and went for one.

`I don't care enough about spaces, single/double quotes, string interpolation and semicolons to make a hard rule about those. Do what you like when you write code, but don't go around changing it in existing code.`
I'd say it's better to have a guideline for the code. If an entire file is consistently spaced/quoted etc., it's easy to follow that pattern. If there are different styles within a single file, it lends to more pattern and less readability. It's a matter of a few keystrokes to make the editor automagically replace all indentation with tabs and make the quotes uniform.

Doing it all in one commit will also prevent code-reformatting-issues pollute future feature related diffs.
