### ISSUE TITLE
Refactor code in /static

### ISSUE THREAD

**Issue by nitzel** [NoHatCoder/Playtak#6]
- Replace all occurences of `var` with `let` and `const`
- Use arrow functions where appropriate
- Replace objects like `server` with a `Server` class and create an instance of it. This should not change any behavior but should allow editors to provide types for methods and member variables as well as show only relevant suggestions

**Comment by NoHatCoder** [comment]
Please don't do any of this, none of this is maintainability issues. `var` vs `let` vs `const` is mostly inconsequential, arrow functions are a bit harder to read, but otherwise make no difference, and JavaScript classes are not better than plain objects.

**Comment by nitzel** [comment]
I'm not saying that `var` and plain objects don't work. 
However to utilize the modern editors' autocompletion and code suggestions classes are required, as they can't infer the types within plain objects:
![image](https://user-images.githubusercontent.com/8362046/106642091-d98bc580-657f-11eb-9642-81a709931af7.png)
![image](https://user-images.githubusercontent.com/8362046/106642206-f88a5780-657f-11eb-8f32-49bc39542e94.png)




- `const` will prevent us from changing variables that shouldn't be changed. Using more `const` and assigning to new variable names instead of reassigning the old variable (e.g. `text = text.trim()` / `const trimmedText = text.trim()`) does also help with understandign code
- `let` could help prevent scope-related bugs
- arrow functions don't set `this` while `function ()` does. I feel the readability of arrow functions is pretty good, but that might be just different taste


I might be a bit biased as I'm only working with typescript professionally.

**Edit**: I was wrong, typings can be inferred from methods of plain objects as well, as long as these are defined above the code that uses them.
